version: "2.3"
services:
  base: &base
    image: kfujikawa/docker-nlp:${TAG:-latest}
    network_mode: "bridge"
    init: true
  en:
    <<: *base
    build:
      context: .
      target: en
  ja:
    <<: *base
    image: kfujikawa/docker-nlp-ja:${TAG:-latest}
    build:
      context: .
      target: ja
  jupyter: &jupyter
    <<: *base
    ports:
      - "${PORT:-8888}:${PORT:-8888}"
    command:
      bash -c "
      jupyter lab --ip 0.0.0.0 --allow-root --port ${PORT:-8888}
      "
