name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: docker login
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
      run: docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS

    - name: Build the Docker image
      run: TAG=latest docker-compose build

    - name: push image [en]
      run: docker push kfujikawa/docker-nlp:latest

    - name: push image [ja]
      run: docker push kfujikawa/docker-nlp-ja:latest
