name: Build Docker Image

on:
  push:
    branches:
    - develop

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build the Docker image [en]
      run: TAG=latest docker-compose build en

    - name: Build the Docker image [ja]
      run: TAG=latest docker-compose build ja
