name: Build Docker Image [Schedule]

on:
  schedule:
    - cron: "0 0 * * 6" # UTC (am 9:00 JST every Saturday) 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build the Docker image [en]
        run: TAG=latest docker-compose build en

      - name: Build the Docker image [ja]
        run: TAG=latest docker-compose build ja
